# Generated by Django 4.2.9 on 2024-02-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_places_delete_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
    ]
